<MoodSelect>:
    orientation: "vertical"
    padding: 50
    spacing: 20

    Label:
        text: "What's your mood today?"
        size_hint_y: None
        height: 30

    GridLayout:
        cols: 3
        spacing: 10
        size_hint_y: None
        height: 80

        

    

    Label:
        id: song_label
        text: ""
        size_hint_y: None
        height: 30
        color: (0, 1, 0, 1)
